---
# tasks file for kibana

    - name: group 'kibana' check
      group:
       name: kibana
       state: present
    - name: Add user 'kibana'
      user:
       name: kibana
       shell: /bin/bash
       groups: kibana
       append: yes
    - name: Upload  tar.gz kibana from remote URL
      get_url:
       url: "http://192.168.1.15/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
       dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
       mode: 0755
       timeout: 60
       force: true
       validate_certs: false
      register: get_kibana
      until: get_kibana is succeeded
      tags: kibana
    - name: Create directory for kibana
      file:
        state: directory
        owner: kibana
        group: kibana
        path: "{{ kibana_home }}"
        mode: 0755
      tags: kibana
    - name: Extract kibana in the installation directory
      become: true
      become_user: kibana
      unarchive:
          copy: false
          src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "{{ kibana_home }}"
          extra_opts: [ --strip-components=1 ]
          creates: "{{ kibana_home }}/bin/kibana"
      tags: kibana
    - name: Set environment Kibana
      become: true
      template:
       src: templates/kibana.sh.j2
       dest: /etc/profile.d/kibana.sh
       mode: 0755
      tags: kibana
